export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const FETCH_PODUCTS_START = "FETCH_PODUCTS_START";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILED = "FETCH_PRODUCTS_FAILED";

export const SELL_PRODUCT_START = "SELL_PRODUCT_START";
export const SELL_PRODUCT_SUCCESS = "SELL_PRODUCT_SUCCESS";
export const SELL_PRODUCT_FAIL = "SELL_PRODUCT_FAIL";
export const SELL_INIT = "SELL_INIT";
